development:
  adapter: sqlite3
  database: db/development.sqlite3xmasc
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: xmasc
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
